"use strict";
exports.__esModule = true;
exports.kangarooImage = exports.koalaImage = exports.raccoonImage = exports.foxImage = exports.redpandaImage = exports.pandaImage = exports.catImage = exports.dogImage = exports.kangarooFact = exports.koalaFact = exports.raccoonFact = exports.foxFact = exports.redpandaFact = exports.pandaFact = exports.catFact = exports.dogFact = void 0;
var facts_1 = require("./functions/facts");
exports.dogFact = facts_1.dogFact;
exports.catFact = facts_1.catFact;
exports.pandaFact = facts_1.pandaFact;
exports.redpandaFact = facts_1.redpandaFact;
exports.foxFact = facts_1.foxFact;
exports.raccoonFact = facts_1.raccoonFact;
exports.koalaFact = facts_1.koalaFact;
exports.kangarooFact = facts_1.kangarooFact;
var images_1 = require("./functions/images");
exports.dogImage = images_1.dogImage;
exports.catImage = images_1.catImage;
exports.pandaImage = images_1.pandaImage;
exports.redpandaImage = images_1.redpandaImage;
exports.foxImage = images_1.foxImage;
exports.raccoonImage = images_1.raccoonImage;
exports.koalaImage = images_1.koalaImage;
exports.kangarooImage = images_1.kangarooImage;
